spring.application.name=spotly
spring.datasource.url=jdbc:postgresql://localhost:5432/spotly
spring.datasource.username=spotly
spring.datasource.password=spotly_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
